### ISSUE TITLE
[BUG]: AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

### ISSUE THREAD

**Issue by pariskang** [hpcaitech/ColossalAI#2938]
### 🐛 Describe the bug

Description:

When I running the command "python main.py --logdir /tmp/ -t -b configs/Teyvat/train_colossalai_teyvat.yaml" to rekoad the diffusion model, I encountered the following error:

AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'
Steps to Reproduce:

Clone the repository.
Run the command "python main.py --logdir /tmp/ -t -b configs/Teyvat/train_colossalai_teyvat.yaml".
Expected Behavior:

The command should run without any errors.

Actual Behavior:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/ColossalAI/examples/images/diffusion/main.py:535 in <module>                               │
│                                                                                                  │
│   532 │   sys.path.append(os.getcwd())                                                           │
│   533 │                                                                                          │
│   534 │   parser = get_parser()                                                                  │
│ ❱ 535 │   parser = Trainer.add_argparse_args(parser)                                             │
│   536 │                                                                                          │
│   537 │   opt, unknown = parser.parse_known_args()                                               │
│   538 │   if opt.name and opt.resume:                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

Additional Context:

The error message suggests that there is a problem with the "Trainer" object and its "add_argparse_args" attribute. Can u help me to resolve it. Thank u.

**Comment by Camille7777** [comment]
Hello, could I know your version of Pytorch Lightning in your environment?

I had the same "AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'" error with the lastest version of **lightning==2.0.0rc1** (Release on Mar 2, 2023), but I tried with **lightning==1.9.0** which is the same as [https://github.com/hpcaitech/ColossalAI/blob/main/examples/images/diffusion/requirements.txt], the above bug disappeared.

**Comment by allanchan339** [comment]
Hi, same issue here, using stable version of pytorch lighnining=2.0, just installed from conda

**Comment by seungyeon-seo** [comment]
I have same issue. my version is 2.0.0

**Comment by beingPurple** [comment]
Same issue, version is 2.02

**Comment by EvergreenTree** [comment]
https://github.com/Lightning-AI/lightning/pull/16708

**Comment by Owen718** [comment]
Same issue! version is 2.0.3

**Comment by thechidiya** [comment]
Hi,

I'm experiencing the same issue pytorch_lightning version is 2.0.4.

**Comment by mevanekanayake** [comment]
I installed pip install pytorch-lightning==1.06 and it WORKED!!

**Comment by GKeppler** [comment]
same issue

**Comment by LightingMc** [comment]
Same error on pl_version: 

'2.0.2'

**Comment by alfredwallace7** [comment]
Same with 2.2.1

**Comment by Alvov1** [comment]
Same here. Pl 2.2.1

**Comment by HuangJiameng** [comment]
I found this problem solved with pytorch_lightning==1.6.3

**Comment by oscar066** [comment]
same error with the pytorch_lightining == 2.2.4

**Comment by MasterHow** [comment]
same with 2.1.0

**Comment by Park-yebin** [comment]
same with 2.2.0 either
Looking at the previous logs, the problem continues to occur repeatedly. Is there any post expressing your position on this?
Sorry to say this but it's a little frustrating. The version is updated, but the error is still not resolved and the code is unusable. I wish I could know what the situation is.

**Comment by soumickmj** [comment]
Same issue 2.3.3

**Comment by Bernice123** [comment]
same issue 2.4.0

**Comment by HoseinHashemi** [comment]
Same issue with pytorch-lightning 2.4.0

**Comment by gulucaptain** [comment]
same issue with pytorch-lightning=='2.5.1'

**Comment by knightnemo** [comment]
Hi, so what is the potential fix for this problem? Would be super helpful.
